# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9e027ee9d96fd17011ccd3422bd77e8df0a5e05c80c8708ca9eebb6402822c83cef4ef9d422d7231eaf1c1ce9bef1bc3f05c04e48fedeaa6d63cd1607834391

test:
  secret_key_base: 09a3e4be86df17e9db7e78264c610a0d1c9422f764cadcdd0846c3ed1e46fcff7e6394e089d2289f996695500c8814586d7bb2157b72b133531308d6ecaa8482

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
